### PR TITLE
Import test data as part of CI

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by bjornharrtell** [comment]
It's not going well.. CI says:

```
#!/bin/bash -eo pipefail
export ORACLE_PATH="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/misc/oracle"
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.PUNKTINFOTYPENAMESPACE.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.OBSERVATIONTYPENAMESPACE.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.SRIDNAMESPACE.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.PUNKTINFOTYPE.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.SRIDTYPE.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.PUNKT.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.PUNKTINFO.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.KOORDINAT.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.GEOMETRIOBJEKT.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
awk -f misc/deobjectidify.awk test/fixtures/sql/data/FIRE_ADM.OBSERVATION.sql | sqlplus64 -S fire/fire@//localhost:1521/xe
run login.sql
sqlterminator ";" (hex 3b)
sqlblanklines OFF
sqlterminator ";" (hex 3b)
sqlblanklines ON
ready login.sql
SP2-0734: unknown command beginning "﻿SET DEF..." - rest of line ignored.
Insert into PUNKTINFOTYPENAMESPACE
            *
ERROR at line 1:
ORA-00913: too many values
```

**Comment by bjornharrtell** [comment]
Manual inspection of deobjectidify.awk (nice hack btw...) result seems ok so not sure what is going on here.

**Comment by bjornharrtell** [comment]
Problem is that default awk (mawk) on Ubuntu 18.04 doesn't produce the correct output. With gawk we get further but run into other issues.

**Comment by bjornharrtell** [comment]
Currently known remaining issue - https://github.com/Kortforsyningen/FIRE-DDL/issues/24.

**Comment by busstoptaktik** [comment]
> Currently known remaining issue - Kortforsyningen/FIRE-DDL#24.

So @AsgerPetersen you could probably review/accept/squash/merge this PR by now (merging is currently blocked)?

**Comment by bjornharrtell** [comment]
@AsgerPetersen this is now working including population of GEOMETRIOBJEKT so this should now be ready to merge, will you approve?

**Pull request merged**
