### PR TITLE
Add sagsevent to koordinat when inserting beregning

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@klavspc this should resolve the constraint issue `ORA-01400: cannot insert NULL into ("FIRE"."KOORDINAT"."SAGSEVENTID")``you got into when trying to insert beregning.

**Comment by AsgerPetersen** [comment]
We still need code to close existing koordinater, as I see it.

**Comment by bjornharrtell** [comment]
@AsgerPetersen - yep I'm aware that part is not done yet. I got to thinking about if it would be sensible or not to do it as a trigger.

**Comment by bjornharrtell** [comment]
Also, I'm not certain about how we make sure koordinat is related to the correct punkt in all this.

**Comment by AsgerPetersen** [comment]
Ensuring the right relation between koordinat and punkt is the responsibility of the client. A koordinat does not make any sense without its relation to a punkt.

**Comment by bjornharrtell** [comment]
Ok but so who is responsible for creating the punkt in the first place? I suppose we need `indset_punkt`.

**Comment by AsgerPetersen** [comment]
The time line for creation of these objects is typically
1) punkt and geometriobjekt
2) observation
3) beregning and koordinat

We definitely need a method for inserting points. MAYBE that method should require that the punkt has a geometriobjekt as it is important for the functionality of the API.

**Pull request merged**
